description: Hire me!
email: an241@duke.edu
theme: jekyll-theme-minimal
# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
  url: ./
- text: Add a new page
  internal: true
  url: add-a-new-page
- text: Configure the Guide
  internal: true
  url: configure-the-guide
- text: GitHub Setup
  internal: true
  url: github
- text: Create a Glossary
  glossary: true
- text: Edit this Repo
  internal: false
  url: https://github.com/DCgov/guides-template

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: guides-template
  description: 
  url: https://github.com/DCgov/guides-template
